pool:
  vmImage: 'ubuntu-latest'

parameters:
-  name: db_pass
   type: string
   displayName: Database password
steps:   
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'export PATH="$PATH:$HOME/.dotnet/tools/"'
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    projects: 'web/FMM/FMM.csproj'
    custom: 'ef migrations script'
    arguments: '--output $(build.artifactstagingdirectory)/migrations.sql -i'