pool:
  vmImage: 'ubuntu-latest'

parameters:
-  name: db_pass
   type: string
   displayName: Database password
steps:   
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls web -al'
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    projects: 'web/FMM/FMM.sln'
    custom: 'ef migrations script'
    arguments: '--output $(build.artifactstagingdirectory)\migrations.sql -i'