pool:
  vmImage: 'ubuntu-latest'

parameters:
-  name: db_pass
   type: string
   displayName: Database password
steps:   
- task: UseDotNet@2
  inputs: 
    packageType: 'sdk'
    version: '2.2.x'
  displayName: Specify dotnet core 2.2.x sdk
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    projects: 'FMM.csproj'
    custom: 'ef'
    arguments: 'migrations script --output $(build.artifactstagingdirectory)/migrations.sql -i'
    workingDirectory: '$(System.DefaultWorkingDirectory)/web/FMM/'