pool:
  vmImage: 'ubuntu-latest'

variables:
  SUBSCRIPTION_NAME: "Azure-1" 

steps:  
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Azure subscription 1(ff581936-424c-495e-a9ed-0c247bdd4d78)'
    KeyVaultName: 'fmm-dev'
    SecretsFilter: 'cr-create'
    RunAsPreJob: true
- task: AzurePowerShell@5
  displayName: "Get Azure DevOps service connection"
  inputs:
    azureSubscription: "$(SUBSCRIPTION_NAME)"
    ScriptType: InlineScript
    inline: |
      Install-Module azure-devops -Force -AllowClobber
      az extension add --name azure-devops
      echo $(cr-create) | az devops login
      az devops configure --defaults organization=https://dev.azure.com/turelit project=fundacjaMamMarzenie --use-git-aliases true
      $env.sc_list = az devops service-endpoint list

- task: AzureCLI@2
  displayName: "Find Azure DevOps service connection"
  inputs:
    azureSubscription: "$(SUBSCRIPTION_NAME)"
    addSpnToEnvironment: true
    scriptType: ps
    scriptLocation: "inlineScript"
    inlineScript: |
      write-host $env.sc_list